---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  yum: 
    name: ntp 
    state: present
  when: ansible_os_family == "Debian"
  tags: ntp

- name: Install ntp
  yum: 
    name: chrony 
    state: present
  when: ansible_os_family == "RedHat"
#  tags: chrony

- name: Install common dependencies
  yum: 
    name: "{{ item }}"
    state: installed
  when: ansible_os_family == "RedHat"
  with_items:
   - python3-libselinux
   - python3-libsemanage
   - firewalld

- name: Configure ntp file
  template: 
    src: ntp.conf.j2 
    dest: /etc/ntp.conf
  tags: ntp
  when: ansible_os_family == "Debian"
  notify: restart ntp

- name: Configure chronyd file
  template: 
    src: chrony.conf.j2 
    dest: /etc/chrony.conf
  tags: chronyd
  when: ansible_os_family == "RedHat"
  notify: restart chronyd

- name: Start the ntp service
  service: 
    name: ntp 
    state: started 
    enabled: yes
  tags: ntp
  when: ansible_os_family == "Debian"

- name: Start the ntp service
  service: 
    name: chronyd 
    state: started 
    enabled: yes
  tags: chrony
  when: ansible_os_family == "RedHat"
