---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  yum: 
    name: ntp 
    state: present
  when: ansible_os_family == "Debian"
  tags: ntp

- name: Install ntp
  yum: 
    name: ntp 
    state: present
  when: ansible_os_family == "RedHat"
  tags: ntp

- name: Install common dependencies
  yum: 
    name: "{{ item }}"
    state: installed
  when: ansible_os_family == "RedHat"
  with_items:
   - libselinux-python
   - libsemanage-python
   - firewalld

- name: Install common dependencies
  yum: 
    name: "{{ item }}"
    state: installed
  when: ansible_os_family == "Debian"
  with_items:
   - libselinux-python
   - libsemanage-python
   - firewalld

- name: Configure ntp file
  template: 
    src: ntp.conf.j2 
    dest: /etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: 
    name: ntpd 
    state: started 
    enabled: yes
  tags: ntp
