---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: restart ntp
  service: 
    name: ntpd 
    state: restarted

- name: restart chronyd 
  service:
    name: "{{ services }}"
    state: started
    enabled: yes
  become: true
  vars:
    services:
    - chrony
